name: Website Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run website in container
      run: docker run -d --name my-website -p 8080:80 -v $(pwd):/usr/share/nginx/html nginx

    - name: Install playwright
      run: npm install --save-dev playwright

    - name: Run playwright tests
      run: npm test
